/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package photoshop;

import java.io.IOException;

import photoshop.filters.*;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        try {
            Image imageIn = new Image("app/src/main/resources/In/img_003.jpeg");
            imageIn.show();

            Image imageOut = new Image("app/src/main/resources/Out/img_003.jpeg");
            
            Filter medianFilter = new MedianFilterGray(imageIn, imageOut, 2);
            medianFilter.apply();

            System.out.println("Applied Median Filter");

            imageIn.close();
            imageOut.show();
            imageOut.close();

        } catch (IOException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }

    }
}
